from __future__ import annotations

from dashboard_service_alerts import (
    clone_alert_rule,
    create_alert_rule,
    delete_alert_rule,
    fetch_alert_deliveries,
    fetch_alert_rules,
    fetch_recent_alerts,
    parse_alert_rule_payload,
    reset_alerts,
    reset_faults,
    send_test_alert,
    update_alert_rule,
)
from dashboard_service_core import (
    FIRING_LOG_PHOTOS_DIR,
    HISTORY_BUCKET_PRESETS,
    HISTORY_WINDOWS,
    alert_rule_row_to_payload,
    build_fault_diagnostics,
    fetch_window_events,
    format_sample_age,
    get_dashboard_state_value,
    normalize_iso_utc,
    open_readonly_connection,
    open_readwrite_connection,
    parse_snapshot_captured_at,
    row_to_payload,
    sanitize_uploaded_photo_name,
    segment_to_dict,
    set_dashboard_state_value,
    table_exists,
    table_has_column,
)
from dashboard_service_history import (
    _auto_bucket_for_span,
    create_event_marker,
    fetch_events,
    fetch_faults,
    fetch_history,
    fetch_history_between,
    fetch_history_with_resolution,
)
from dashboard_service_logs import (
    build_firing_log_markdown,
    create_firing_log,
    fetch_firing_log_detail,
    fetch_firing_logs,
    parse_firing_log_payload,
    refresh_firing_log_related_data,
    sync_firing_log_related_data,
    update_firing_log,
    upload_firing_log_photo,
)
from dashboard_service_profiles import (
    activate_profile,
    create_profile,
    delete_profile,
    fetch_active_profile_run,
    fetch_profile_by_id,
    fetch_profiles,
    parse_profile_payload,
    parse_profile_row,
    stop_profile_tracking,
    update_profile,
)
from dashboard_service_status import (
    capture_camera_snapshot,
    default_watchdog_settings,
    fetch_alert_channel_settings,
    fetch_alert_channel_status,
    fetch_camera_status,
    fetch_dashboard_preferences,
    fetch_dashboard_status,
    fetch_watchdog_settings,
    update_alert_channel_settings,
    update_dashboard_preferences,
    update_watchdog_settings,
)
